# Generated by Django 5.2.3 on 2025-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
