# Generated by Django 5.2.3 on 2025-06-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_healthdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHealthData',
        ),
    ]
