# Generated by Django 4.2.23 on 2025-07-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_delete_userhealthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadedreport'),
        ),
    ]
